### ISSUE TITLE
Text List error: CR_TextList.make_list() missing 1 required positional argument: 'loops'

### ISSUE THREAD

**Issue by GitWilburn** [Suzie1/ComfyUI_Comfyroll_CustomNodes#116]
Having an issue with the CR Text List node. Tried using the text workflow to make sure it wasn't just me and I got the error on the example workflow as well.

I think the issue is this line in nodes_list.py that was changed a few weeks ago:
    def make_list(self, multiline_text, start_index, max_rows, loops):

When I removed ",loops" it worked as expected.

Full error text:
ERROR:root:Traceback (most recent call last):
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CR_TextList.make_list() missing 1 required positional argument: 'loops'

**Comment by liulsg** [comment]
the same problem

**Comment by jojorne** [comment]
"loops" is not used anywhere in the code and can be safely removed.
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/d78b780ae43fcf8c6b7c6505e6ffb4584281ceca/nodes/nodes_list.py#L79

**Comment by jojorne** [comment]
"loops" is not used anywhere in the code and can be safely removed.
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/d78b780ae43fcf8c6b7c6505e6ffb4584281ceca/nodes/nodes_list.py#L79
```python
def make_list(self, multiline_text, start_index, max_rows):
```

**Comment by GitWilburn** [comment]
> "loops" is not used anywhere in the code and can be safely removed.
> 
> https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/d78b780ae43fcf8c6b7c6505e6ffb4584281ceca/nodes/nodes_list.py#L79
> 
> ```python
> def make_list(self, multiline_text, start_index, max_rows):
> ```

Confirmed. This is how I resolved on my local instance and it works fine.

**Comment by zhenyuanzhou** [comment]
Thank you, this also solve my problem.

**Comment by HWiese1980** [comment]
Why has this not found its way into the current leading branch?

**Comment by rjgoif** [comment]
Would love it if the author @Suzie1 would incorporate this into the build, but I fear that the Comfyroll suite is starting to look abandoned.

**Comment by XieDeWu** [comment]
"CR Text Cycle" can use?

**Comment by dule1970** [comment]
Why this issue is unfindable anywhere o the entire interwebernet?
