### ISSUE TITLE
TypeError: 'type' object is not subscriptable 

### ISSUE THREAD

**Issue by martin-yin** [Suzie1/ComfyUI_Comfyroll_CustomNodes#151]
```code
** ComfyUI startup time: 2024-04-01 23:05:03.133932
[2024-04-01 23:05] ** Platform: Windows
[2024-04-01 23:05] ** Python version: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
[2024-04-01 23:05] ** Python executable: C:\Program Files\python\python.exe
[2024-04-01 23:05] ** Log path: D:\ai-draw\ComfyUI\comfyui.log
[2024-04-01 23:05] 
Prestartup times for custom nodes:
[2024-04-01 23:05]    0.0 seconds: D:\ai-draw\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-04-01 23:05] 
Total VRAM 2048 MB, total RAM 16194 MB
[2024-04-01 23:05] Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
[2024-04-01 23:05] Set vram state to: LOW_VRAM
[2024-04-01 23:05] Device: cuda:0 NVIDIA GeForce GTX 1050 : cudaMallocAsync
[2024-04-01 23:05] VAE dtype: torch.float32
[2024-04-01 23:05] Using pytorch cross attention
[2024-04-01 23:05] Adding extra search path checkpoints D:\ai-draw\sd.webui\webui\models/Stable-diffusion
[2024-04-01 23:05] Adding extra search path configs D:\ai-draw\sd.webui\webui\models/Stable-diffusion
[2024-04-01 23:05] Adding extra search path vae D:\ai-draw\sd.webui\webui\models/VAE
[2024-04-01 23:05] Adding extra search path loras D:\ai-draw\sd.webui\webui\models/Lora
[2024-04-01 23:05] Adding extra search path loras D:\ai-draw\sd.webui\webui\models/LyCORIS
[2024-04-01 23:05] Adding extra search path upscale_models D:\ai-draw\sd.webui\webui\models/ESRGAN
[2024-04-01 23:05] Adding extra search path upscale_models D:\ai-draw\sd.webui\webui\models/RealESRGAN
[2024-04-01 23:05] Adding extra search path upscale_models D:\ai-draw\sd.webui\webui\models/SwinIR
[2024-04-01 23:05] Adding extra search path embeddings D:\ai-draw\sd.webui\webui\embeddings
[2024-04-01 23:05] Adding extra search path hypernetworks D:\ai-draw\sd.webui\webui\models/hypernetworks
[2024-04-01 23:05] Adding extra search path controlnet D:\ai-draw\sd.webui\webui\extensions/sd-webui-controlnet
[2024-04-01 23:05] Adding extra search path checkpoints path/to/comfyui/models/checkpoints/
[2024-04-01 23:05] Adding extra search path clip path/to/comfyui/models/clip/
[2024-04-01 23:05] Adding extra search path clip_vision path/to/comfyui/models/clip_vision/
[2024-04-01 23:05] Adding extra search path configs path/to/comfyui/models/configs/
[2024-04-01 23:05] Adding extra search path controlnet path/to/comfyui/models/controlnet/
[2024-04-01 23:05] Adding extra search path embeddings path/to/comfyui/models/embeddings/
[2024-04-01 23:05] Adding extra search path loras path/to/comfyui/models/loras/
[2024-04-01 23:05] Adding extra search path upscale_models path/to/comfyui/models/upscale_models/
[2024-04-01 23:05] Adding extra search path vae path/to/comfyui/models/vae/
[2024-04-01 23:05] ### Loading: ComfyUI-Inspire-Pack (V0.69.2)
[2024-04-01 23:05] ### Loading: ComfyUI-Manager (V2.11)
[2024-04-01 23:05] ### ComfyUI Revision: 2094 [13064645] | Released on '2024-03-31'
[2024-04-01 23:05] HTTPS proxies https://127.0.0.1:7890 are not supported, ignoring
[2024-04-01 23:05] HTTPS proxies https://127.0.0.1:7890 are not supported, ignoring
[2024-04-01 23:05] HTTPS proxies https://127.0.0.1:7890 are not supported, ignoring
[2024-04-01 23:05] HTTPS proxies https://127.0.0.1:7890 are not supported, ignoring
[2024-04-01 23:05] Exception in thread Thread-5:
[2024-04-01 23:05] Traceback (most recent call last):
[2024-04-01 23:05]   File "C:\Users\martin-yin\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 1173, in _create_direct_connection
[2024-04-01 23:05]     hosts = await asyncio.shield(host_resolved)
[2024-04-01 23:05]   File "C:\Users\martin-yin\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 884, in _resolve_host
[2024-04-01 23:05]     addrs = await self._resolver.resolve(host, port, family=self._family)
[2024-04-01 23:05]   File "C:\Users\martin-yin\AppData\Roaming\Python\Python38\site-packages\aiohttp\resolver.py", line 33, in resolve
[2024-04-01 23:05]     infos = await self._loop.getaddrinfo(
[2024-04-01 23:05]   File "C:\Program Files\python\lib\asyncio\base_events.py", line 825, in getaddrinfo
[2024-04-01 23:05]     return await self.run_in_executor(
[2024-04-01 23:05]   File "C:\Program Files\python\lib\concurrent\futures\thread.py", line 57, in run
[2024-04-01 23:05]     result = self.fn(*self.args, **self.kwargs)
[2024-04-01 23:05]   File "C:\Program Files\python\lib\socket.py", line 918, in getaddrinfo
[2024-04-01 23:05]     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[2024-04-01 23:05] socket.gaierror: [Errno 11004] getaddrinfo failed
[2024-04-01 23:05] 
The above exception was the direct cause of the following exception:

[2024-04-01 23:05] Traceback (most recent call last):
[2024-04-01 23:05]   File "C:\Program Files\python\lib\threading.py", line 932, in _bootstrap_inner
[2024-04-01 23:05]     self.run()
[2024-04-01 23:05]   File "C:\Program Files\python\lib\threading.py", line 870, in run
[2024-04-01 23:05]     self._target(*self._args, **self._kwargs)
[2024-04-01 23:05]   File "D:\ai-draw\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2446, in <lambda>
[2024-04-01 23:05]     threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
[2024-04-01 23:05]   File "C:\Program Files\python\lib\asyncio\runners.py", line 44, in run
[2024-04-01 23:05]     return loop.run_until_complete(main)
[2024-04-01 23:05]   File "C:\Program Files\python\lib\asyncio\base_events.py", line 616, in run_until_complete
[2024-04-01 23:05]     return future.result()
[2024-04-01 23:05]   File "D:\ai-draw\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2443, in default_cache_update
[2024-04-01 23:05]     await asyncio.gather(a, b, c, d)
[2024-04-01 23:05]   File "D:\ai-draw\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2431, in get_cache
[2024-04-01 23:05]     json_obj = await get_data(uri, True)
[2024-04-01 23:05]   File "D:\ai-draw\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 574, in get_data
[2024-04-01 23:05]     async with session.get(uri) as resp:
[2024-04-01 23:05]   File "C:\Users\martin-yin\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 1194, in __aenter__
[2024-04-01 23:05]     self._resp = await self._coro
[2024-04-01 23:05]   File "C:\Users\martin-yin\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 578, in _request
[2024-04-01 23:05]     conn = await self._connector.connect(
[2024-04-01 23:05]   File "C:\Users\martin-yin\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 544, in connect
[2024-04-01 23:05]     proto = await self._create_connection(req, traces, timeout)
[2024-04-01 23:05]   File "C:\Users\martin-yin\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 911, in _create_connection
[2024-04-01 23:05]     _, proto = await self._create_direct_connection(req, traces, timeout)
[2024-04-01 23:05]   File "C:\Users\martin-yin\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
[2024-04-01 23:05]     raise ClientConnectorError(req.connection_key, exc) from exc
[2024-04-01 23:05] aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
[2024-04-01 23:05] Traceback (most recent call last):
  File "D:\ai-draw\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\ai-draw\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\__init__.py", line 21, in <module>
    from .node_mappings import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ai-draw\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\node_mappings.py", line 11, in <module>
    from .nodes.nodes_xygrid import *
  File "D:\ai-draw\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\nodes_xygrid.py", line 16, in <module>
    from .functions_xygrid import create_images_grid_by_columns, Annotation
  File "D:\ai-draw\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\functions_xygrid.py", line 20, in <module>
    class Annotation():
  File "D:\ai-draw\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\functions_xygrid.py", line 21, in Annotation
    column_texts: list[str]
TypeError: 'type' object is not subscriptable

[2024-04-01 23:05] Cannot import D:\ai-draw\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes module for custom nodes: 'type' object is not subscriptable
[2024-04-01 23:05] [92m[tinyterraNodes] [32mLoaded[0m
[2024-04-01 23:05] 
Import times for custom nodes:
[2024-04-01 23:05]    0.0 seconds: D:\ai-draw\ComfyUI\custom_nodes\websocket_image_save.py
[2024-04-01 23:05]    0.0 seconds: D:\ai-draw\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
[2024-04-01 23:05]    0.1 seconds (IMPORT FAILED): D:\ai-draw\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
[2024-04-01 23:05]    0.3 seconds: D:\ai-draw\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-04-01 23:05]    0.6 seconds: D:\ai-draw\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
[2024-04-01 23:05] 
[2024-04-01 23:05] Starting server

[2024-04-01 23:05] To see the GUI go to: http://127.0.0.1:8188
[2024-04-01 23:05] FETCH DATA from: D:\ai-draw\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[2024-04-01 23:05] HTTPS proxies https://127.0.0.1:7890 are not supported, ignoring
[2024-04-01 23:05] FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-04-01 23:05] HTTPS proxies https://127.0.0.1:7890 are not supported, ignoring
[2024-04-01 23:05] [ComfyUI-Manager] Due to a network error, switching to local mode.
=> custom-node-list.json
=> Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
[2024-04-01 23:05] FETCH DATA from: D:\ai-draw\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json
[2024-04-01 23:05] FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-04-01 23:05] HTTPS proxies https://127.0.0.1:7890 are not supported, ignoring
[2024-04-01 23:05] [ComfyUI-Manager] Due to a network error, switching to local mode.
=> extension-node-map.json
=> Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
[2024-04-01 23:05] FETCH DATA from: D:\ai-draw\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

```
![image](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/19162008/11c183b7-b99d-424a-83c8-3ae0b122ee38)

![image](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/19162008/3e362934-2a71-4173-b1e5-08afa505212b)

[debuger-workflow.json](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/files/14824965/debuger-workflow.json)

my ComfyUI  and ComfyUI-Manager  already the latest version

**Comment by martin-yin** [comment]
![image](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/19162008/9004f1fb-cae4-4b24-b873-ba71daf3387a)
Perhaps I need this version of Python
![image](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/assets/19162008/84b65d51-e588-4337-8e4a-6dab1a11c7ad)
