### ISSUE TITLE
No image for image list loader throws exception.

### ISSUE THREAD

**Issue by MilitantHitchhiker** [Suzie1/ComfyUI_Comfyroll_CustomNodes#162]
Add exception handling please.

|CR Load Image List: No images found.
!!! Exception during processing!!! object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 95, in get_output_data
    output_is_list = [False] * len(results[0])
                               ^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

**Comment by MilitantHitchhiker** [comment]
Submitted a pull request with fix.
