### ISSUE TITLE
Error on Halftone Filter execution

### ISSUE THREAD

**Issue by gonzalu** [Suzie1/ComfyUI_Comfyroll_CustomNodes#168]
Hello,

I am getting the following error when trying to run the CR Halftone Filter. No matter what image I use as input, I get:

```
!!! Exception during processing!!! wrong number of bands
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\nodes_graphics_filter.py", line 202, in halftone_effect
    new_image = Image.merge("CMYK", halftone_images).convert("RGB")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\PIL\Image.py", line 3431, in merge
    raise ValueError(msg)
ValueError: wrong number of bands
```

**Comment by microvswind** [comment]
same here

**Comment by gonzalu** [comment]
> same here

I decided to create my own :D 

https://github.com/gonzalu/ComfyUI_YFG_Comical?tab=readme-ov-file#image-halftone-generator
