### ISSUE TITLE
(IMPORT FAILED)

### ISSUE THREAD

**Issue by Nico53425342** [Suzie1/ComfyUI_Comfyroll_CustomNodes#169]
D:\Desktop\Comfy-UI+EX\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\nodes_list.py:383: SyntaxWarning: invalid escape sequence '\W'
  "optional": {"folder_path": ("STRING", {"default": "C:\Windows\Fonts", "multiline": False}),
D:\Desktop\Comfy-UI+EX\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\nodes_list.py:393: SyntaxWarning: invalid escape sequence '\W'
  def make_list(self, source_folder, start_index, max_rows, folder_path="C:\Windows\Fonts"):
Comfyroll Studio: Failed to load Essential nodes
Comfyroll Studio: Failed to load Graphics nodes
Traceback (most recent call last):
  File "D:\Desktop\Comfy-UI+EX\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Desktop\Comfy-UI+EX\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\__init__.py", line 21, in <module>
    from .node_mappings import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Desktop\Comfy-UI+EX\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\node_mappings.py", line 87, in <module>
    "CR Image Size": CR_ImageSize,
                     ^^^^^^^^^^^^
NameError: name 'CR_ImageSize' is not defined. Did you mean: 'CR_ImageList'?

Cannot import D:\Desktop\Comfy-UI+EX\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes module for custom nodes: name 'CR_ImageSize' is not defined
Traceback (most recent call last):
  File "D:\Desktop\Comfy-UI+EX\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Desktop\Comfy-UI+EX\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\__init__.py", line 1, in <module>
    from .ttNpy.tinyterraNodes import TTN_VERSIONS

**Comment by I-kk-a** [comment]
Comfyroll Studio: Failed to load Graphics nodes
Traceback (most recent call last):
  File "C:\StableDiffusion\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\__init__.py", line 21, in <module>
    from .node_mappings import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\node_mappings.py", line 87, in <module>
    "CR Image Size": CR_ImageSize,
                     ^^^^^^^^^^^^
NameError: name 'CR_ImageSize' is not defined

Cannot import C:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes module for custom nodes: name 'CR_ImageSize' is not defined

**Comment by OuticNZ** [comment]
This was due to a ComfyUI update.  ComfyUI has since been updated to maintain backward compatibility for some custom nodes - https://github.com/comfyanonymous/ComfyUI/commit/16a493a19042227baadd939fc095305716ae58db

Update ComfyUI and it's resolved for now

**Comment by Nico53425342** [comment]
no more problem, thx for you help
