### ISSUE TITLE
Error Importing Node in Latest ComfyUI Version

### ISSUE THREAD

**Issue by nikbogman** [Suzie1/ComfyUI_Comfyroll_CustomNodes#184]
I've encountered an error while trying to import a node in the most recent version of ComfyUI. 

`
Comfyroll Studio: Failed to load Essential nodes
Comfyroll Studio: Failed to load Graphics nodes
Traceback (most recent call last):
  File "/root/nodes.py", line 1930, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/custom_nodes/ComfyUI_Comfyroll_CustomNodes/__init__.py", line 21, in <module>
    from .node_mappings import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/root/custom_nodes/ComfyUI_Comfyroll_CustomNodes/node_mappings.py", line 50, in <module>
    "CR Image Output": CR_ImageOutput,
                       ^^^^^^^^^^^^^^
NameError: name 'CR_ImageOutput' is not defined

Cannot import /root/custom_nodes/ComfyUI_Comfyroll_CustomNodes module for custom nodes: name 'CR_ImageOutput' is not defined

Import times for custom nodes:
   0.0 seconds: /root/custom_nodes/websocket_image_save.py
   0.0 seconds: /root/custom_nodes/comfyui_controlnet_aux
   0.1 seconds (IMPORT FAILED): /root/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   1.7 seconds: /root/custom_nodes/efficiency-nodes-comfyui
   2.2 seconds: /root/custom_nodes/comfyui-reactor-node
`

I would appreciate any help in resolving this issue. Thank you!

**Comment by hhx2018** [comment]
same error
