### ISSUE TITLE
can't find the system fonts in WSL 

### ISSUE THREAD

**Issue by if-ai** [Suzie1/ComfyUI_Comfyroll_CustomNodes#75]
```
[ERROR] An error occurred while retrieving information for the 'CR Font File List' node.
Traceback (most recent call last):
  File "/home/impactframes/ComfyUI/server.py", line 418, in get_object_info
    out[x] = node_info(x)
  File "/home/impactframes/ComfyUI/server.py", line 396, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/impactframes/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes.py", line 728, in INPUT_TYPES
    font_dir = os.path.join(system_root, 'Fonts')
  File "/home/impactframes/micromamba/envs/comfy/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by if-ai** [comment]
i fix it by specifying the share fonts folder on the nodes.py font_dir = "/usr/share/fonts/truetype"
