### ISSUE TITLE
 import piexif ModuleNotFoundError: No module named 'piexif'

### ISSUE THREAD

**Issue by GuoYangGit** [Suzie1/ComfyUI_Comfyroll_CustomNodes#83]
Traceback (most recent call last):
  File "E:\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\__init__.py", line 8, in <module>
    from .live_node_mappings import LIVE_NODE_CLASS_MAPPINGS, LIVE_NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\live_node_mappings.py", line 20, in <module>
    from .nodes.nodes_list import *
  File "E:\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\nodes_list.py", line 13, in <module>
    import piexif
ModuleNotFoundError: No module named 'piexif'

**Comment by Suzie1** [comment]
hi, thanks for flagging this
i'll do a quick update and let you know when its fixed

**Comment by Suzie1** [comment]
Hi again, its fixed now on github. You can try update or git pull.

**Comment by Suzie1** [comment]
closing, let me know if its still an issue
