### ISSUE TITLE
Pattern nodes (not working)

### ISSUE THREAD

**Issue by K3nt3L** [Suzie1/ComfyUI_Comfyroll_CustomNodes#96]
Hi
The pattern nodes failing to render images.
Thanks for maintaining this useful  custom nodes :)

(I updated Comfy and the nodes yesterday, and reinstall Comfy & all the nodes today. 2 days ago, it worked fine).

Matrix  SD console output :
__________________________________________________________

Error occurred when executing CR Halftone Grid:

Can't find a usable init.tcl in the following directories:
D:/Matrix/Data/Assets/lib/tcl8.6 D:/Matrix/Data/Packages/ComfyUI/venv/lib/tcl8.6 D:/Matrix/Data/Packages/ComfyUI/lib/tcl8.6 D:/Matrix/Data/Packages/ComfyUI/venv/library D:/Matrix/Data/Packages/ComfyUI/library D:/Matrix/Data/Packages/ComfyUI/tcl8.6.12/library D:/Matrix/Data/Packages/tcl8.6.12/library

This probably means that Tcl wasn't installed properly.

File "D:\Matrix\Data\Packages\ComfyUI\execution.py", line 154, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\Matrix\Data\Packages\ComfyUI\execution.py", line 84, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\Matrix\Data\Packages\ComfyUI\execution.py", line 77, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\Matrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\nodes_graphics_matplot.py", line 135, in halftone
fig, ax = plt.subplots(figsize=(width/100,height/100))
File "D:\Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\matplotlib\pyplot.py", line 1598, in subplots
fig = figure(**fig_kw)
File "D:\Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\matplotlib\pyplot.py", line 934, in figure
manager = new_figure_manager(
File "D:\Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\matplotlib\pyplot.py", line 465, in new_figure_manager
return _get_backend_mod().new_figure_manager(*args, **kwargs)
File "D:\Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\matplotlib\backend_bases.py", line 3402, in new_figure_manager
return cls.new_figure_manager_given_figure(num, fig)
File "D:\Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\matplotlib\backend_bases.py", line 3407, in new_figure_manager_given_figure
return cls.FigureCanvas.new_manager(figure, num)
File "D:\Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\matplotlib\backend_bases.py", line 1785, in new_manager
return cls.manager_class.create_with_canvas(cls, figure, num)
File "D:\Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 486, in create_with_canvas
window = tk.Tk(className="matplotlib")
File "D:\Matrix\Data\Assets\Python310\tkinter\__init__.py", line 2299, in __init__
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)

**Comment by Suzie1** [comment]
Hi, thanks for reporting this. I just ran my test cases for the Pattern nodes and they are all working okay.
I'm not sure why tcl is triggering an error. It is not an import in the Comfyroll code. I'm not familiar with Matrix SD but is it possible this erro is related to your Matrix build?
The Pattern nodes didn't have any recent changes. I will update my Comfy today and see if that causes an issue. I usually update once a week. Suzie

**Comment by K3nt3L** [comment]
Thanks. I'm guessing that I have an issue between my Python and the venvs... But the issue is still there when I 'm using my old Comfy, outside Matrix.
I have installed too much things last weeks, it's becoming a mess.

**Comment by K3nt3L** [comment]
By the way, I solved the issue and made some tests. 
The nodes are working on a fresh standalone portable version.
I reinstalled Matrix : the pattern nodes, for now, can't work with Comfy in Matrix.

**Comment by Suzie1** [comment]
Hi, I'm glad its solved. I'm sorry they don't work in Matrix. If you can identify why, I would be happy to do a fix.
Suzie

**Comment by mthompson0220** [comment]
Latest Comfy UI:

Traceback (most recent call last):
  File "D:\AI\SD\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\SD\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\__init__.py", line 21, in <module>
    from .node_mappings import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\AI\SD\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\node_mappings.py", line 132, in <module>
    "CR Halftone Grid": CR_HalftoneGrid,
                    ^^^^^^^^^^^^^^^
NameError: name 'CR_HalftoneGrid' is not defined

Dedicated env with all else working.

**Comment by K3nt3L** [comment]
I can't say how and why, but now, it's working fine with Matrix.

**Comment by xixiU** [comment]
> Latest Comfy UI:
> 
> Traceback (most recent call last): File "D:\AI\SD\ComfyUI\nodes.py", line 1893, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "D:\AI\SD\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes__init__.py", line 21, in from .node_mappings import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "D:\AI\SD\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\node_mappings.py", line 132, in "CR Halftone Grid": CR_HalftoneGrid, ^^^^^^^^^^^^^^^ NameError: name 'CR_HalftoneGrid' is not defined
> 
> Dedicated env with all else working.


just Comment out line 132 in node_mappings works.

**Comment by LivingWithHippos** [comment]
"fixed" this:

```sh
node_mappings.py", line 133, in <module>
    "CR Halftone Grid": CR_HalftoneGrid,
                        ^^^^^^^^^^^^^^^
NameError: name 'CR_HalftoneGrid' is not defined
```

it should be imported here

https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/d78b780ae43fcf8c6b7c6505e6ffb4584281ceca/node_mappings.py#L17

I added a custom print outside the try catch

```py
try:
    from .nodes.nodes_graphics_matplot import *
    from .nodes.nodes_graphics_text import *
    from .nodes.nodes_graphics_layout import *
    from .nodes.nodes_graphics_filter import *
    from .nodes.nodes_graphics_template import *
    from .nodes.nodes_graphics_pattern import *
except ImportError:
    print("\033[34mComfyroll Studio: \033[92mFailed to load Graphics nodes\033[0m")

print("Custom Import")
from .nodes.nodes_graphics_matplot import CR_HalftoneGrid
```

and the error switched to

```sh
ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_matplot.py", line 18, in <module>
    import pip
ModuleNotFoundError: No module named 'pip'
```

which is where `nodes_graphics_matplot` tries to install the missing matplotlib using pip, but if pip is not installed the exception thrown will be shadowed by the  `except ImportError` above

https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/d78b780ae43fcf8c6b7c6505e6ffb4584281ceca/nodes/nodes_graphics_matplot.py#L15-L20

in my case `pip` was not installed since I'm using `uv` so I just added matplotlib manually with `uv add matplotlib`
